# 
# docker-compose.yml — определяет сервисы для разработки и тестирования.

#Что нужно сделать:
#  - Настроить сервисы для:
#      - PostgreSQL (или MySQL) с начальной базой.
#      - Приложения Spring Boot (если нужно).
#  - Открыть нужные порты (например, 5432, 8080).
#  - Настроить volume для хранения данных БД.
#TODO healthcheck

services:
  postgres:
    image: postgres:15
    container_name: bank_postgres
    restart: unless-stopped

    env_file:
      - .env

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    container_name: bank_app
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "${APP_PORT}:8080"
    env_file:
      - .env
    environment:
      SERVER_PORT: 8080
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      CARD_CRYPTO_SECRET: ${CARD_CRYPTO_SECRET}
    volumes:
      - ./logs:/app/logs

volumes:
  postgres_data:
