

server:
  port: ${SERVER_PORT:8080}

spring:
  # Database connection
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/bank_db}
    username: ${DB_USER:bank_user}
    password: ${DB_PASSWORD:bank_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate        # managed by Liquibase
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/migration/db.changelog-master.xml
    enabled: true

# JWT configuration
app:
  jwt:
    secret: ${JWT_SECRET:mySuperSecretKeyForJwtGenerationThatShouldBeAtLeast32CharactersLong}
    expiration: ${JWT_EXPIRATION:86400000}  # 24 hours in ms

  card:
    crypto:
      secret: ${CARD_CRYPTO_SECRET:myCardPanEncryptionSecretThatShouldBeAtLeast32CharactersLong}

# Swagger / OpenAPI
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    url: /docs/openapi.yaml

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE